server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /weather {
    proxy_pass http://host.docker.internal:8000/weather;
  }

  location /history {
    proxy_pass http://host.docker.internal:8000/history;
  }

  location /health {
    proxy_pass http://host.docker.internal:8000/health;
  }
}
